Import patches-unapplied version 2.31.1 to ubuntu/xenial-proposed
Imported using git-ubuntu import.

Changelog parent: a08a55a482df2a6e8075cd4d60425fe9949e1c1f

diff --git a/tests/main/snapctl-services/task.yaml b/tests/main/snapctl-services/task.yaml
--- a/tests/main/snapctl-services/task.yaml
+++ b/tests/main/snapctl-services/task.yaml
@@ -1,6 +1,7 @@
 summary: Check that own services can be controlled by snapctl
 
-kill-timeout: 3m
+kill-timeout: 5m
+
 environment:
     SERVICEOPTIONFILE: /var/snap/test-snapd-service/current/service-option
 
@@ -8,9 +9,6 @@ restore: |
     rm -f $SERVICEOPTIONFILE
 
 execute: |
-    echo "The test is disabled for now until the functionality is restored"
-    exit 0
-
     wait_for_service() {
         retry=5
         while ! snap services $1 | MATCH $2; do
@@ -71,3 +69,11 @@ execute: |
 
     echo "And service could get the new service-option set from the hook"
     wait_for_file_change $SERVICEOPTIONFILE "^foo$"
+
+    echo "Reinstalling the snap with configure hook calling snapctl restart works"
+    snap set test-snapd-service command=restart
+    install_local test-snapd-service
+    if journalctl|grep -q "error running snapctl"; then
+        echo "snapctl should not report errors"
+        exit 1
+    fi
